---
title: "Shiny App Ph.D. Delay Plot"
author: "Ihnwhi Heo"
date: '2020 9 28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plot

```{r}
library(ggplot2)
library(extrafont)

x <- base::sample(100, 100, replace = FALSE)
x <- sort(x)
y <- 10 + 5*x - 0.05*x^2
y

dat <- data.frame(x,y)
colnames(dat) <- c("Age", "Delay")
plot <- ggplot(dat, aes(x,y)) + 
    geom_point() +
  theme_bw() +
  ggtitle("A Positive Linear Effect and a Negative Quadratic Effect of Age on Delay") +
  xlab("Age (in years)") +
  ylab("Delay (in months)") +
  annotate(geom="text", x=50, y=150, family="Candara", size = 4.5,
           label=paste("Delay ==", 10, "+", 5, "*" ,"~Age", "-", 0.05,
           "~Age^2"),
           parse=TRUE) +
  scale_y_continuous(breaks = seq(0,150,25), limits=c(0,160)) +
  theme(text=element_text(family="Candara"),
        plot.title = element_text(size = 14, color="black", hjust=0.5),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13))
plot
```

